# Pandas Practice Notebook

This notebook demonstrates basic pandas operations:
- Creating DataFrames from dictionaries
- Concatenating DataFrames (rows and columns)
- Reading CSV files
- Data manipulation

In [1]:
import pandas as pd

new_data = {
    "name": ["Example 1", "Example 2"],
    "description": [
        "This is an example JSON file.",
        "This is another example JSON file.",
    ],
    "version": ["1.0.0", "2.0.0"],
}

new_data2 = {
    "name": ["Example 3", "Example 4"],
    "description": [
        "This is yet another example JSON file.",
        "This is one more example JSON file.",
    ],
    "version": ["3.0.0", "4.0.0"],
}

column_data = {
    "third": [
        "Additional data 1",
        "Additional data 2",
    ]
}

df_one = pd.DataFrame(new_data)
df_two = pd.DataFrame(new_data2)
df_three = pd.DataFrame(column_data)
df_combined = pd.concat([df_one, df_two])
df_combined = pd.concat([df_combined, df_three])
df_combined.reset_index(drop=True, inplace=True)
df_combined

,name,description,version,third
0,Example 1,This is an example JSON file.,1.0.0,NaN
1,Example 2,This is another example JSON file.,2.0.0,NaN
2,Example 3,This is yet another example JSON file.,3.0.0,NaN
3,Example 4,This is one more example JSON file.,4.0.0,NaN
4,NaN,NaN,NaN,Additional data 1
5,NaN,NaN,NaN,Additional data 2

In [2]:
import pandas as pd

new_data = {
    "name": ["Example 1", "Example 2"],
    "description": [
        "This is an example JSON file.",
        "This is another example JSON file.",
    ],
    "version": ["1.0.0", "2.0.0"],
}

new_data2 = {
    "name": ["Example 3", "Example 4"],
    "description": [
        "This is yet another example JSON file.",
        "This is one more example JSON file.",
    ],
    "version": ["3.0.0", "4.0.0"],
}

column_data = {
    "third": [
        "Additional data 1",
        "Additional data 2",
    ]
}

df_one = pd.DataFrame(new_data)
df_two = pd.DataFrame(new_data2)
df_three = pd.DataFrame(column_data)
df_combined = pd.concat([df_one, df_two])
df_combined = pd.concat([df_combined, df_three], axis=1)
df_combined.reset_index(drop=True, inplace=True)
df_combined

,name,description,version,third
0,Example 1,This is an example JSON file.,1.0.0,Additional data 1
1,Example 2,This is another example JSON file.,2.0.0,Additional data 2
2,Example 3,This is yet another example JSON file.,3.0.0,Additional data 1
3,Example 4,This is one more example JSON file.,4.0.0,Additional data 2

In [3]:
import pandas as pd
df_csv = pd.read_csv("../data/example-2.csv")
print(f"This is the csv dataframe: \n {df_csv}")

back_to_csv = df_csv.to_csv()
print(f"This is the original csv: \n {back_to_csv}")

This is the csv dataframe:
              Name  Age           City  Salary   Department
0        John Doe   28       New York   75000  Engineering
1      Jane Smith   32  San Francisco   85000    Marketing
2     Bob Johnson   45        Chicago   65000        Sales
3  Alice Williams   29         Boston   72000  Engineering
4   Charlie Brown   38        Seattle   90000      Product
5    Diana Prince   26         Austin   68000       Design
6       Eve Davis   41         Denver   95000   Management
7    Frank Miller   33       Portland   78000  Engineering
8       Grace Lee   35          Miami   82000    Marketing
9    Henry Wilson   30        Atlanta   71000        Sales
This is the original csv:
 ,Name,Age,City,Salary,Department
0,John Doe,28,New York,75000,Engineering
1,Jane Smith,32,San Francisco,85000,Marketing
2,Bob Johnson,45,Chicago,65000,Sales
3,Alice Williams,29,Boston,72000,Engineering
4,Charlie Brown,38,Seattle,90000,Product
5,Diana Prince,26,Austin,68000,Design
6,Eve Davis,41,Denver,95000,Management
7,Frank Miller,33,Portland,78000,Engineering
8,Grace Lee,35,Miami,82000,Marketing
9,Henry Wilson,30,Atlanta,71000,Sales

In [4]:
import pandas as pd
df_csv = pd.read_csv("../data/example-3.csv", header=None)
print(f"This is the csv dataframe: \n {df_csv}")

This is the csv dataframe:
                 0   1              2      3            4
0        John Doe  28       New York  75000  Engineering
1      Jane Smith  32  San Francisco  85000    Marketing
2     Bob Johnson  45        Chicago  65000        Sales
3  Alice Williams  29         Boston  72000  Engineering
4   Charlie Brown  38        Seattle  90000      Product
5    Diana Prince  26         Austin  68000       Design
6       Eve Davis  41         Denver  95000   Management
7    Frank Miller  33       Portland  78000  Engineering
8       Grace Lee  35          Miami  82000    Marketing
9    Henry Wilson  30        Atlanta  71000        Sales